version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://astro:astro@cluster0.alvokl5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3001"
    environment:
      - BACKEND_URL=http://backend:5001
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    name: todo-app-network
    driver: bridge

volumes:
  mongodb_data: 